class ItemInfo;
class CfgWeapons {
    class synixe_mgp_vest_battle_belt_assaulter_base;
    class synixe_mgp_vest_battle_belt_hgunner_base;
    UNDERCOVER(synixe_mgp_vest_battle_belt_assaulter_base,ItemInfo,synixe_mgp_vest_battle_belt_assaulter_aor1,Belt Assaulter (AOR1));
    UNDERCOVER(synixe_mgp_vest_battle_belt_assaulter_base,ItemInfo,synixe_mgp_vest_battle_belt_assaulter_aor2,Belt Assaulter (AOR2));
    UNDERCOVER(synixe_mgp_vest_battle_belt_assaulter_base,ItemInfo,synixe_mgp_vest_battle_belt_assaulter_blk,Belt Assaulter (Black));
    UNDERCOVER(synixe_mgp_vest_battle_belt_assaulter_base,ItemInfo,synixe_mgp_vest_battle_belt_assaulter_cb,Belt Assaulter (Coyote Brown));
    UNDERCOVER(synixe_mgp_vest_battle_belt_assaulter_base,ItemInfo,synixe_mgp_vest_battle_belt_assaulter_khk,Belt Assaulter (Khaki));
    UNDERCOVER(synixe_mgp_vest_battle_belt_assaulter_base,ItemInfo,synixe_mgp_vest_battle_belt_assaulter_mc,Belt Assaulter (MC));
    UNDERCOVER(synixe_mgp_vest_battle_belt_assaulter_base,ItemInfo,synixe_mgp_vest_battle_belt_assaulter_rgr,Belt Assaulter (Ranger Green));
    UNDERCOVER(synixe_mgp_vest_battle_belt_assaulter_base,ItemInfo,synixe_mgp_vest_battle_belt_assaulter_wht,Belt Assaulter (White));
    UNDERCOVER(synixe_mgp_vest_battle_belt_hgunner_base,ItemInfo,synixe_mgp_vest_battle_belt_hgunner_aor1,Belt Hgunner (AOR1));
    UNDERCOVER(synixe_mgp_vest_battle_belt_hgunner_base,ItemInfo,synixe_mgp_vest_battle_belt_hgunner_aor2,Belt Hgunner (AOR2));
    UNDERCOVER(synixe_mgp_vest_battle_belt_hgunner_base,ItemInfo,synixe_mgp_vest_battle_belt_hgunner_blk,Belt Hgunner (Black));
    UNDERCOVER(synixe_mgp_vest_battle_belt_hgunner_base,ItemInfo,synixe_mgp_vest_battle_belt_hgunner_cb,Belt Hgunner (Coyote Brown));
    UNDERCOVER(synixe_mgp_vest_battle_belt_hgunner_base,ItemInfo,synixe_mgp_vest_battle_belt_hgunner_khk,Belt Hgunner (Khaki));
    UNDERCOVER(synixe_mgp_vest_battle_belt_hgunner_base,ItemInfo,synixe_mgp_vest_battle_belt_hgunner_mc,Belt Hgunner (MC));
    UNDERCOVER(synixe_mgp_vest_battle_belt_hgunner_base,ItemInfo,synixe_mgp_vest_battle_belt_hgunner_rgr,Belt Hgunner (Ranger Green));
    UNDERCOVER(synixe_mgp_vest_battle_belt_hgunner_base,ItemInfo,synixe_mgp_vest_battle_belt_hgunner_wht,Belt Hgunner (White));
};
